import '../entities/student.dart';
import '../repositories/student_repository.dart';

class AddStudent {
  final StudentRepository repository;

  AddStudent(this.repository);

  Future<void> call(Student student) {
    // In a real app, ID would be generated by backend or UUID
    return repository.updateStudent(student);
  }
}
