// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZPgU8_pEk9_EfMSfA9c3L6VfZzatCH7c',
    appId: '1:527209708828:web:a2f65df706f7aab70b8ed9',
    messagingSenderId: '527209708828',
    projectId: 'church-6eb05',
    authDomain: 'church-6eb05.firebaseapp.com',
    storageBucket: 'church-6eb05.firebasestorage.app',
    measurementId: 'G-86NGE59S6T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrEulD0bfBXgxYJC15zHZ57ZFUp_NwXpI',
    appId: '1:527209708828:android:ed3ed10b7a5aeb6d0b8ed9',
    messagingSenderId: '527209708828',
    projectId: 'church-6eb05',
    storageBucket: 'church-6eb05.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATQjY08dRXUr3jUrJOOvBfqqrQVdA1bs0',
    appId: '1:527209708828:ios:7cd18dca976d42300b8ed9',
    messagingSenderId: '527209708828',
    projectId: 'church-6eb05',
    storageBucket: 'church-6eb05.firebasestorage.app',
    iosBundleId: 'com.csms.csms',
  );
}
